name: Upload Files to Server
on:
  push:
    branches: [ test ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      name: Run sshpass commands
      uses: matheusvanzan/sshpass-action@v1
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        run: |
          sshpass -e scp -o stricthostkeychecking=no -r . username@host:/mnt/src/image-processing
